### ISSUE TITLE
Redefine the input built-in python function in Section 2.3 codes of SIT742P01A-Python.ipynb

### ISSUE THREAD

**Issue by ghost** [tulip-lab/sit742#1]
Running the code step by step till the Section 2.4 codes,
nInput  = input('Enter you number here:\n') 
You will find that it will show TypeError: 'str' object is not callable.

Reason:
Due to in the Section 2.3 codes, we have defined input = '45.6'. It means that we had redefine what input() means. But input() is the built-in Python function used in the Section 2.4 codes, and we don't want to change it.

Solution:
Use a different name for the local variable "input" in Section 2.3 codes, it should be as below:

input_value= '45.6'
type(input_value)

weight = float(input_value)
weight
type(weight)

input_value= 'David'
weight = float(input_value)

**Comment by tuliplab** [comment]
Thanks @assignmentupload 

It has been resolved.
