### ISSUE TITLE
SIT742P02C-OperationsinPandas - Reindexing : Fill_value does not work

### ISSUE THREAD

**Issue by priyakumari19** [tulip-lab/sit742#18]
df_3.reindex(range(6, 0), fill_value=0) values does not give any output.
It seems something is missing in this

![Bug](https://user-images.githubusercontent.com/47842845/54864906-c1f32b80-4db1-11e9-9174-b241b5d46741.png)

**Comment by ghost** [comment]
Hi there,
Many thanks for your feedback.
It should be a typo.
I will revise it and update it to GitHub.

You can change it with the below code and try it:

df_3.reindex(range(0, 6), fill_value=0)

Regards,

Zhi Liu
