### ISSUE TITLE
Spark Image URL Changed

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/sit742#24]
For all Apache Spark related notebook or assignment, the URL for downloading the image file is now: 

!wget -q https://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz

**Comment by tuliplab** [comment]
@ZiweiHou 

Did those URL changed for all remaining Spark notebooks?

If not, at least don't close this issue and find time to fix.

**Comment by ZiweiHou** [comment]
updated URLs in 07ABC, 10AB and Ass2
