### ISSUE TITLE
SIT742P07B: Apache Spark MLlib (1) gets a 404 error

### ISSUE THREAD

**Issue by dbow073** [tulip-lab/sit742#41]
Hi, the associated page for  SIT742P07B: Apache Spark MLlib (1),  https://github.com/tulip-lab/sit742/blob/master/Jupyter/SIT742P07B-MLlib-DataType.ipynb gets a 404 error, so seems to be missing.
Thanks.

**Comment by ghost** [comment]
Hi Mate,
You use the wrong URL, it should be the https://github.com/tulip-lab/sit742/blob/master/Jupyter/SIT742P07B-MLlib_DataType.ipynb.
Thanks.

Regards,

Zhi Liu

**Comment by dbow073** [comment]
Ok, thanks for that .
Cheers
Derryn
