### ISSUE TITLE
SIT742P01D-TextProcess.ipynb has a problem loading on colab

### ISSUE THREAD

**Issue by Ayodeji-python** [tulip-lab/sit742#44]
![unable to load page](https://user-images.githubusercontent.com/57605386/77369270-46f09680-6db2-11ea-835f-4f66a8eb0eff.PNG)

**Comment by tuliplab** [comment]
Thanks for reporting, and I have fixed this issue. The notebook is now ready for loading in Colab.

**Comment by Ayodeji-python** [comment]
Thank you A/prof
