### ISSUE TITLE
I'm unable to load a txt file from my gitup repository. please help

### ISSUE THREAD

**Issue by Ayodeji-python** [tulip-lab/sit742#47]
![challenge with code2](https://user-images.githubusercontent.com/57605386/78534206-64e7dd80-782d-11ea-8738-0498a8374d50.JPG)
![challenge with code3](https://user-images.githubusercontent.com/57605386/78534209-66b1a100-782d-11ea-9ca9-219547d89a54.JPG)

**Comment by tuliplab** [comment]
@Ayodeji-python please check the following:

1. whether the URL you provided is really linking to a file that can be downloaded? 

2. You may just upload that csv file directly into your google drive folder, and then make sure that it is under the folder. Then you can use np.loadtxt or csv load to open the file.

You can also post to CloudDeakin discussion forum, and I believe that some others may experience similar issue, and you can learn from them.

**Comment by Ayodeji-python** [comment]
Thank you very much for your prompt response. However, I'm still experiencing the same issue when I uploaded the file to my google drive. below is the link to my code snippet. I have gone through topics on the discussion group and saw no similar issue. And posted the issue with no response. Please help.
https://colab.research.google.com/drive/13QDV8Ewx_skIWYV7cSUhafwTWqFeoX-r#scrollTo=cThmJx78Mlwh&line=8&uniqifier=1

**Comment by tuliplab** [comment]
If you have time on Thursday morning, please attend one SIT742 Help Hub session. The tutor will go through the details with you. Maybe need you to put that csv file in a common place first. Say dropbox.

**Comment by Ayodeji-python** [comment]
ok, sir, I would continue to try. Thanks
