### ISSUE TITLE
Index_col typo _SIT742PO3A

### ISSUE THREAD

**Issue by wuyoscar** [tulip-lab/sit742#53]
`
#Before fix
weather_mar2012 = pd.read_csv(url, skiprows=0, index_col='Date/Time', parse_dates=True, encoding='latin1')

#After fix
weather_mar2012 = pd.read_csv(url, skiprows=0, index_col='Date/Time (LST)', parse_dates=True, encoding='latin1')
`

**Comment by ZiweiHou** [comment]
Hi @wuyoscar,


In our latest SIT742P03A notebook, we already fixed this typo. Please track the latest version of weekly materials.


Best wishes,
Ziwei
