### ISSUE TITLE
SIT742P04A

### ISSUE THREAD

**Issue by wuyoscar** [tulip-lab/sit742#56]
Hi, just found a minor typo here.
Plz Check

![WechatIMG4](https://user-images.githubusercontent.com/72287536/114823566-0a516c00-9e07-11eb-9c77-95826eea7533.jpeg)
<img width="640" alt="Screen Shot 2021-04-15 at 4 24 15 pm" src="https://user-images.githubusercontent.com/72287536/114823585-0de4f300-9e07-11eb-94f9-224da6415ec9.png">

**Comment by tuliplab** [comment]
@zhangdabao361  please fix the color of the histogram for that hair ones.
