### ISSUE TITLE
ARM notebook - arima min_length 

### ISSUE THREAD

**Issue by AleDonisi** [tulip-lab/sit742#58]
hi 
it looks like min_length is not a valid parameter for apriori. From the function help, I can see just max length.
SIT742P04D-ARMining.ipynb

Regards

**Comment by tuliplab** [comment]
@zhangdabao361 please check whether this is a coding bug in P04D.

**Comment by AleDonisi** [comment]
@zhangdabao361  Is a change required in the notebook?

**Comment by zhangdabao361** [comment]
> @zhangdabao361 Is a change required in the notebook?

Thank you for raising this question.
Yes, I have made changes to the notebook.
