### ISSUE TITLE
SIT742: Big Data Analytics - Advanced Data Types - List Slicing issue

### ISSUE THREAD

**Issue by mrinal2278** [tulip-lab/sit742#66]
https://github.com/tulip-lab/sit742/blob/main/Jupyter/M02-Python/M02G-AdvDataTypes.ipynb

1. 
```
l = [1, 2, 3, 4]
l[-2:]    # From the second right to the beginning
Output: [3, 4]
```

From the comment it seems like the expected output is [1,2,3] or [3,2,1]. 
May be the comment needs to change? (like From the second right to the end of the list?)

I could get [1,2,3] by : l[:-2] using negative index and l[:3] normally..

2.
Second, joint() is the inverse of split. >>> I believe we mean join()?

**Comment by chriszhangpodo** [comment]
correct the issue on M02G
