### ISSUE TITLE
Minor correction in the text explaining Anomaly Score

### ISSUE THREAD

**Issue by drabhishekk14** [tulip-lab/sit742#67]
Please consider to update 
1) "Similarly we can find the values of anomaly column by calling the predict() function of the trained model and passing the **salary** as parameter." 
2) As expected, the data frame has three columns now: **salary**, scores and anomaly.

"arrival" is the parameter.

Thanks,
Abhishek.

**Comment by chriszhangpodo** [comment]
Corrected on M05C
