### ISSUE TITLE
The length should be 7 but only 6 elements were given

### ISSUE THREAD

**Issue by Avinashbudige** [tulip-lab/sit742#68]
![image](https://github.com/tulip-lab/sit742/assets/52130922/d96129ec-b4a6-4118-8543-4e40cdea32c0)

I have added a new element below is the corrected code.
![image](https://github.com/tulip-lab/sit742/assets/52130922/ba4561c1-7ddc-4f03-8d19-cc6253fc060f)

**Comment by ZiweiHou** [comment]
Thank you for raising this. It is now resolved.
