### ISSUE TITLE
Typo in M02G-AdvDataTypes.ipynb

### ISSUE THREAD

**Issue by BuzzKanga** [tulip-lab/sit742#72]
There is a typo in M02G-AdvDataTypes.ipynb

This is what is notebook:

'+' is used for concatenation operation, which repeats a list a given number of times.

 [10, 20, 30, 40 ] + [50, 60]

[50, 60]*3

** List slices ** Slicing operation allows to retrieve a slice of of the list. i.e. a part of the sequence. The sliding operation uses square brackets to enclose an optional pair of numbers separated by a colon. Again, to count the position of items from left(first item), start from
. If you count the position from right(last item), start from

This is what should be in the notebook

'+' is used for concatenation operation, 

 [10, 20, 30, 40 ] + [50, 60]

'*' is used for to repeat a list a given number of times. 

m = [50, 60]*3

**List slices** 

Slicing operation allows to retrieve a slice of of the list. i.e. a part of the sequence. The sliding operation uses square brackets to enclose an optional pair of numbers separated by a colon. Again, to count the position of items from left(first item), start from
. If you count the position from right(last item), start from

**Comment by haiyangxia** [comment]
Thank BuzzKanga, the supposed changes make sense. Our team will be working on addressing the issue accordingly. Have a good night.

**Comment by tuliplab** [comment]
Maybe you can also consider a pull request

**Comment by tuliplab** [comment]
@haiyangxia If fixed, please close this issue. Thanks.
